name: Create Repository from Template

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Name of the new repository'
        required: true

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Repository
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        REPO_NAME=${{ github.repository_owner }}/${{ github.event.inputs.repo_name }}
        TEMPLATE_REPO=bhanuraina/simple-java-maven-app
        ACCESS_TOKEN=$GH_PAT
        API_URL="https://api.github.com/repos/$TEMPLATE_REPO/generate"
        
        response=$(curl -X POST -H "Authorization: token $ACCESS_TOKEN" -d "{\"owner\":\"${{ github.repository_owner }}\",\"name\":\"${{ github.event.inputs.repo_name }}\"}" $API_URL)
        
        echo "$response"
